name: r2
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38hd77b12b_8
  - ca-certificates=2025.2.25=haa95532_0
  - cccl=2.3.2=h47f531a_0
  - certifi=2024.8.30=py38haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cccl=12.4.127=haa95532_2
  - cuda-cccl_win-64=12.4.127=haa95532_2
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-opencl-dev=12.4.127=0
  - cuda-profiler-api=12.4.127=haa95532_1
  - cuda-runtime=12.1.0=0
  - cuda-version=12.4=hbda6634_3
  - filelock=3.13.1=py38haa95532_0
  - freetype=2.12.1=ha860e81_0
  - gmpy2=2.1.2=py38h7f96b67_0
  - idna=3.7=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.4=py38haa95532_0
  - jpeg=9e=h827c3e9_3
  - lcms2=2.16=hb4a4139_0
  - lerc=4.0.0=h5da7b33_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.5.147=hd77b12b_1
  - libcurand-dev=10.3.5.147=hd77b12b_1
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.22=h5bf469e_0
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libtiff=4.5.1=h44ae7cf_1
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h3d04722_1
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=2.1.3=py38h2bbff1b_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py38haa95532_0
  - networkx=3.1=py38haa95532_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=1.1.1w=h2bbff1b_0
  - pillow=10.4.0=py38h827c3e9_0
  - pip=20.3.3=py38haa95532_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.5=h5fd99cc_1
  - pytorch=2.2.2=py3.8_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py38h827c3e9_0
  - requests=2.32.3=py38haa95532_0
  - setuptools=75.1.0=py38haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - sympy=1.13.3=py38haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - typing_extensions=4.11.0=py38haa95532_0
  - urllib3=2.2.3=py38haa95532_0
  - vc=14.42=haa95532_4
  - vs2015_runtime=14.42.34433=he0abc0d_4
  - wheel=0.44.0=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - absl-py==2.2.2
      - accelerate==1.0.1
      - addict==2.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - cachetools==5.5.2
      - clean-fid==0.1.35
      - cmake==4.0.3
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - datasets==3.1.0
      - diffusers==0.32.2
      - dill==0.3.8
      - einops==0.8.1
      - evaluate==0.4.3
      - fairscale==0.4.13
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - ftfy==6.2.3
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - huggingface-hub==0.30.2
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - lightning-utilities==0.11.9
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mmcv==1.7.0
      - mmengine==0.10.7
      - multidict==6.1.0
      - multiprocess==0.70.16
      - ninja==1.11.1.4
      - numpy==1.24.4
      - oauthlib==3.2.2
      - open-clip-torch==2.32.0
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.0.3
      - platformdirs==4.3.6
      - polars==1.8.2
      - propcache==0.2.0
      - protobuf==3.20.3
      - psutil==7.0.0
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.7
      - pygments==2.19.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-fid==0.3.0
      - pytorch-lightning==2.4.0
      - pytz==2025.2
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rsa==4.9
      - safetensors==0.5.3
      - scipy==1.10.1
      - six==1.17.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - timm==1.0.22
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch-fidelity==0.3.0
      - torchaudio==2.2.2
      - torchmetrics==1.5.2
      - torchvision==0.17.2
      - tqdm==4.67.1
      - transformers==4.46.3
      - tzdata==2025.2
      - ultralytics==8.3.241
      - ultralytics-thop==2.0.18
      - wcwidth==0.2.14
      - werkzeug==3.0.6
      - xformer==1.0.1
      - xformers==0.0.25
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: C:\miniconda3\envs\r2
